# 设置服务端口
server:
  port: 8092

#设置eureka相关信息
eureka:
  instance:
    hostname: ${spring.application.name}
    ### 实例名称显示IP配置
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
  # 注册到的eureka服务地址


# 服务模块名称
spring:
  application:
    name: ybtUnderWriting
  redis:
    database: 0
    host: 192.168.152.131
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000



