package com.sinosoft.ybtentity;

import java.math.BigDecimal;
import java.util.Date;

public class Lktransstatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.trans_code
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String transCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.bank_code
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.bank_branch
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String bankBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.bank_node
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String bankNode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.bank_operator
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String bankOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.trans_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.funcflag
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String funcflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.transdate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private Date transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.transtime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.managecom
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String managecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.riskcode
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String riskcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.proposal_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String proposalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.prt_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String prtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.pol_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String polNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.edor_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String edorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.tempfee_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String tempfeeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.trans_amnt
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private BigDecimal transAmnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.bank_account
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.rcode
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String rcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.trans_status
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String transStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.status
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.descr
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.temp
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String temp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.client_ip
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.client_port
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String clientPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.service_starttime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private Date serviceStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.service_endtime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private Date serviceEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.makedate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.maketime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.modifydate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LKTransStatus.modifytime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.trans_code
     *
     * @return the value of LKTransStatus.trans_code
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getTransCode() {
        return transCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.trans_code
     *
     * @param transCode the value for LKTransStatus.trans_code
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTransCode(String transCode) {
        this.transCode = transCode == null ? null : transCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.bank_code
     *
     * @return the value of LKTransStatus.bank_code
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.bank_code
     *
     * @param bankCode the value for LKTransStatus.bank_code
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.bank_branch
     *
     * @return the value of LKTransStatus.bank_branch
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.bank_branch
     *
     * @param bankBranch the value for LKTransStatus.bank_branch
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch == null ? null : bankBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.bank_node
     *
     * @return the value of LKTransStatus.bank_node
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getBankNode() {
        return bankNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.bank_node
     *
     * @param bankNode the value for LKTransStatus.bank_node
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setBankNode(String bankNode) {
        this.bankNode = bankNode == null ? null : bankNode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.bank_operator
     *
     * @return the value of LKTransStatus.bank_operator
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getBankOperator() {
        return bankOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.bank_operator
     *
     * @param bankOperator the value for LKTransStatus.bank_operator
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setBankOperator(String bankOperator) {
        this.bankOperator = bankOperator == null ? null : bankOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.trans_no
     *
     * @return the value of LKTransStatus.trans_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.trans_no
     *
     * @param transNo the value for LKTransStatus.trans_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.funcflag
     *
     * @return the value of LKTransStatus.funcflag
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getFuncflag() {
        return funcflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.funcflag
     *
     * @param funcflag the value for LKTransStatus.funcflag
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setFuncflag(String funcflag) {
        this.funcflag = funcflag == null ? null : funcflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.transdate
     *
     * @return the value of LKTransStatus.transdate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.transdate
     *
     * @param transdate the value for LKTransStatus.transdate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.transtime
     *
     * @return the value of LKTransStatus.transtime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.transtime
     *
     * @param transtime the value for LKTransStatus.transtime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTranstime(String transtime) {
        this.transtime = transtime == null ? null : transtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.managecom
     *
     * @return the value of LKTransStatus.managecom
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getManagecom() {
        return managecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.managecom
     *
     * @param managecom the value for LKTransStatus.managecom
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setManagecom(String managecom) {
        this.managecom = managecom == null ? null : managecom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.riskcode
     *
     * @return the value of LKTransStatus.riskcode
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.riskcode
     *
     * @param riskcode the value for LKTransStatus.riskcode
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode == null ? null : riskcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.proposal_no
     *
     * @return the value of LKTransStatus.proposal_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getProposalNo() {
        return proposalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.proposal_no
     *
     * @param proposalNo the value for LKTransStatus.proposal_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setProposalNo(String proposalNo) {
        this.proposalNo = proposalNo == null ? null : proposalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.prt_no
     *
     * @return the value of LKTransStatus.prt_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getPrtNo() {
        return prtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.prt_no
     *
     * @param prtNo the value for LKTransStatus.prt_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setPrtNo(String prtNo) {
        this.prtNo = prtNo == null ? null : prtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.pol_no
     *
     * @return the value of LKTransStatus.pol_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getPolNo() {
        return polNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.pol_no
     *
     * @param polNo the value for LKTransStatus.pol_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setPolNo(String polNo) {
        this.polNo = polNo == null ? null : polNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.edor_no
     *
     * @return the value of LKTransStatus.edor_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getEdorNo() {
        return edorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.edor_no
     *
     * @param edorNo the value for LKTransStatus.edor_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setEdorNo(String edorNo) {
        this.edorNo = edorNo == null ? null : edorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.tempfee_no
     *
     * @return the value of LKTransStatus.tempfee_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getTempfeeNo() {
        return tempfeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.tempfee_no
     *
     * @param tempfeeNo the value for LKTransStatus.tempfee_no
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTempfeeNo(String tempfeeNo) {
        this.tempfeeNo = tempfeeNo == null ? null : tempfeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.trans_amnt
     *
     * @return the value of LKTransStatus.trans_amnt
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public BigDecimal getTransAmnt() {
        return transAmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.trans_amnt
     *
     * @param transAmnt the value for LKTransStatus.trans_amnt
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTransAmnt(BigDecimal transAmnt) {
        this.transAmnt = transAmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.bank_account
     *
     * @return the value of LKTransStatus.bank_account
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.bank_account
     *
     * @param bankAccount the value for LKTransStatus.bank_account
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.rcode
     *
     * @return the value of LKTransStatus.rcode
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getRcode() {
        return rcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.rcode
     *
     * @param rcode the value for LKTransStatus.rcode
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setRcode(String rcode) {
        this.rcode = rcode == null ? null : rcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.trans_status
     *
     * @return the value of LKTransStatus.trans_status
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.trans_status
     *
     * @param transStatus the value for LKTransStatus.trans_status
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus == null ? null : transStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.status
     *
     * @return the value of LKTransStatus.status
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.status
     *
     * @param status the value for LKTransStatus.status
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.descr
     *
     * @return the value of LKTransStatus.descr
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.descr
     *
     * @param descr the value for LKTransStatus.descr
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.temp
     *
     * @return the value of LKTransStatus.temp
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.temp
     *
     * @param temp the value for LKTransStatus.temp
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setTemp(String temp) {
        this.temp = temp == null ? null : temp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.client_ip
     *
     * @return the value of LKTransStatus.client_ip
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.client_ip
     *
     * @param clientIp the value for LKTransStatus.client_ip
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.client_port
     *
     * @return the value of LKTransStatus.client_port
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getClientPort() {
        return clientPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.client_port
     *
     * @param clientPort the value for LKTransStatus.client_port
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setClientPort(String clientPort) {
        this.clientPort = clientPort == null ? null : clientPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.service_starttime
     *
     * @return the value of LKTransStatus.service_starttime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Date getServiceStarttime() {
        return serviceStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.service_starttime
     *
     * @param serviceStarttime the value for LKTransStatus.service_starttime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setServiceStarttime(Date serviceStarttime) {
        this.serviceStarttime = serviceStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.service_endtime
     *
     * @return the value of LKTransStatus.service_endtime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Date getServiceEndtime() {
        return serviceEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.service_endtime
     *
     * @param serviceEndtime the value for LKTransStatus.service_endtime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setServiceEndtime(Date serviceEndtime) {
        this.serviceEndtime = serviceEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.makedate
     *
     * @return the value of LKTransStatus.makedate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.makedate
     *
     * @param makedate the value for LKTransStatus.makedate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.maketime
     *
     * @return the value of LKTransStatus.maketime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.maketime
     *
     * @param maketime the value for LKTransStatus.maketime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setMaketime(String maketime) {
        this.maketime = maketime == null ? null : maketime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.modifydate
     *
     * @return the value of LKTransStatus.modifydate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.modifydate
     *
     * @param modifydate the value for LKTransStatus.modifydate
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LKTransStatus.modifytime
     *
     * @return the value of LKTransStatus.modifytime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LKTransStatus.modifytime
     *
     * @param modifytime the value for LKTransStatus.modifytime
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }
}