package com.sinosoft.ybtentity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LktransstatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public LktransstatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransCodeIsNull() {
            addCriterion("trans_code is null");
            return (Criteria) this;
        }

        public Criteria andTransCodeIsNotNull() {
            addCriterion("trans_code is not null");
            return (Criteria) this;
        }

        public Criteria andTransCodeEqualTo(String value) {
            addCriterion("trans_code =", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotEqualTo(String value) {
            addCriterion("trans_code <>", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeGreaterThan(String value) {
            addCriterion("trans_code >", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeGreaterThanOrEqualTo(String value) {
            addCriterion("trans_code >=", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLessThan(String value) {
            addCriterion("trans_code <", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLessThanOrEqualTo(String value) {
            addCriterion("trans_code <=", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLike(String value) {
            addCriterion("trans_code like", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotLike(String value) {
            addCriterion("trans_code not like", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeIn(List<String> values) {
            addCriterion("trans_code in", values, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotIn(List<String> values) {
            addCriterion("trans_code not in", values, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeBetween(String value1, String value2) {
            addCriterion("trans_code between", value1, value2, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotBetween(String value1, String value2) {
            addCriterion("trans_code not between", value1, value2, "transCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeIsNull() {
            addCriterion("bank_code is null");
            return (Criteria) this;
        }

        public Criteria andBankCodeIsNotNull() {
            addCriterion("bank_code is not null");
            return (Criteria) this;
        }

        public Criteria andBankCodeEqualTo(String value) {
            addCriterion("bank_code =", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotEqualTo(String value) {
            addCriterion("bank_code <>", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeGreaterThan(String value) {
            addCriterion("bank_code >", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_code >=", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLessThan(String value) {
            addCriterion("bank_code <", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLessThanOrEqualTo(String value) {
            addCriterion("bank_code <=", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLike(String value) {
            addCriterion("bank_code like", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotLike(String value) {
            addCriterion("bank_code not like", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeIn(List<String> values) {
            addCriterion("bank_code in", values, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotIn(List<String> values) {
            addCriterion("bank_code not in", values, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeBetween(String value1, String value2) {
            addCriterion("bank_code between", value1, value2, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotBetween(String value1, String value2) {
            addCriterion("bank_code not between", value1, value2, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankBranchIsNull() {
            addCriterion("bank_branch is null");
            return (Criteria) this;
        }

        public Criteria andBankBranchIsNotNull() {
            addCriterion("bank_branch is not null");
            return (Criteria) this;
        }

        public Criteria andBankBranchEqualTo(String value) {
            addCriterion("bank_branch =", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchNotEqualTo(String value) {
            addCriterion("bank_branch <>", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchGreaterThan(String value) {
            addCriterion("bank_branch >", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchGreaterThanOrEqualTo(String value) {
            addCriterion("bank_branch >=", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchLessThan(String value) {
            addCriterion("bank_branch <", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchLessThanOrEqualTo(String value) {
            addCriterion("bank_branch <=", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchLike(String value) {
            addCriterion("bank_branch like", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchNotLike(String value) {
            addCriterion("bank_branch not like", value, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchIn(List<String> values) {
            addCriterion("bank_branch in", values, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchNotIn(List<String> values) {
            addCriterion("bank_branch not in", values, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchBetween(String value1, String value2) {
            addCriterion("bank_branch between", value1, value2, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankBranchNotBetween(String value1, String value2) {
            addCriterion("bank_branch not between", value1, value2, "bankBranch");
            return (Criteria) this;
        }

        public Criteria andBankNodeIsNull() {
            addCriterion("bank_node is null");
            return (Criteria) this;
        }

        public Criteria andBankNodeIsNotNull() {
            addCriterion("bank_node is not null");
            return (Criteria) this;
        }

        public Criteria andBankNodeEqualTo(String value) {
            addCriterion("bank_node =", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeNotEqualTo(String value) {
            addCriterion("bank_node <>", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeGreaterThan(String value) {
            addCriterion("bank_node >", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_node >=", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeLessThan(String value) {
            addCriterion("bank_node <", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeLessThanOrEqualTo(String value) {
            addCriterion("bank_node <=", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeLike(String value) {
            addCriterion("bank_node like", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeNotLike(String value) {
            addCriterion("bank_node not like", value, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeIn(List<String> values) {
            addCriterion("bank_node in", values, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeNotIn(List<String> values) {
            addCriterion("bank_node not in", values, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeBetween(String value1, String value2) {
            addCriterion("bank_node between", value1, value2, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankNodeNotBetween(String value1, String value2) {
            addCriterion("bank_node not between", value1, value2, "bankNode");
            return (Criteria) this;
        }

        public Criteria andBankOperatorIsNull() {
            addCriterion("bank_operator is null");
            return (Criteria) this;
        }

        public Criteria andBankOperatorIsNotNull() {
            addCriterion("bank_operator is not null");
            return (Criteria) this;
        }

        public Criteria andBankOperatorEqualTo(String value) {
            addCriterion("bank_operator =", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorNotEqualTo(String value) {
            addCriterion("bank_operator <>", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorGreaterThan(String value) {
            addCriterion("bank_operator >", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("bank_operator >=", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorLessThan(String value) {
            addCriterion("bank_operator <", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorLessThanOrEqualTo(String value) {
            addCriterion("bank_operator <=", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorLike(String value) {
            addCriterion("bank_operator like", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorNotLike(String value) {
            addCriterion("bank_operator not like", value, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorIn(List<String> values) {
            addCriterion("bank_operator in", values, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorNotIn(List<String> values) {
            addCriterion("bank_operator not in", values, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorBetween(String value1, String value2) {
            addCriterion("bank_operator between", value1, value2, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andBankOperatorNotBetween(String value1, String value2) {
            addCriterion("bank_operator not between", value1, value2, "bankOperator");
            return (Criteria) this;
        }

        public Criteria andTransNoIsNull() {
            addCriterion("trans_no is null");
            return (Criteria) this;
        }

        public Criteria andTransNoIsNotNull() {
            addCriterion("trans_no is not null");
            return (Criteria) this;
        }

        public Criteria andTransNoEqualTo(String value) {
            addCriterion("trans_no =", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotEqualTo(String value) {
            addCriterion("trans_no <>", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoGreaterThan(String value) {
            addCriterion("trans_no >", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoGreaterThanOrEqualTo(String value) {
            addCriterion("trans_no >=", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoLessThan(String value) {
            addCriterion("trans_no <", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoLessThanOrEqualTo(String value) {
            addCriterion("trans_no <=", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoLike(String value) {
            addCriterion("trans_no like", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotLike(String value) {
            addCriterion("trans_no not like", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoIn(List<String> values) {
            addCriterion("trans_no in", values, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotIn(List<String> values) {
            addCriterion("trans_no not in", values, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoBetween(String value1, String value2) {
            addCriterion("trans_no between", value1, value2, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotBetween(String value1, String value2) {
            addCriterion("trans_no not between", value1, value2, "transNo");
            return (Criteria) this;
        }

        public Criteria andFuncflagIsNull() {
            addCriterion("funcflag is null");
            return (Criteria) this;
        }

        public Criteria andFuncflagIsNotNull() {
            addCriterion("funcflag is not null");
            return (Criteria) this;
        }

        public Criteria andFuncflagEqualTo(String value) {
            addCriterion("funcflag =", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagNotEqualTo(String value) {
            addCriterion("funcflag <>", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagGreaterThan(String value) {
            addCriterion("funcflag >", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagGreaterThanOrEqualTo(String value) {
            addCriterion("funcflag >=", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagLessThan(String value) {
            addCriterion("funcflag <", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagLessThanOrEqualTo(String value) {
            addCriterion("funcflag <=", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagLike(String value) {
            addCriterion("funcflag like", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagNotLike(String value) {
            addCriterion("funcflag not like", value, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagIn(List<String> values) {
            addCriterion("funcflag in", values, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagNotIn(List<String> values) {
            addCriterion("funcflag not in", values, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagBetween(String value1, String value2) {
            addCriterion("funcflag between", value1, value2, "funcflag");
            return (Criteria) this;
        }

        public Criteria andFuncflagNotBetween(String value1, String value2) {
            addCriterion("funcflag not between", value1, value2, "funcflag");
            return (Criteria) this;
        }

        public Criteria andTransdateIsNull() {
            addCriterion("transdate is null");
            return (Criteria) this;
        }

        public Criteria andTransdateIsNotNull() {
            addCriterion("transdate is not null");
            return (Criteria) this;
        }

        public Criteria andTransdateEqualTo(Date value) {
            addCriterion("transdate =", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateNotEqualTo(Date value) {
            addCriterion("transdate <>", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateGreaterThan(Date value) {
            addCriterion("transdate >", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateGreaterThanOrEqualTo(Date value) {
            addCriterion("transdate >=", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateLessThan(Date value) {
            addCriterion("transdate <", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateLessThanOrEqualTo(Date value) {
            addCriterion("transdate <=", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateIn(List<Date> values) {
            addCriterion("transdate in", values, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateNotIn(List<Date> values) {
            addCriterion("transdate not in", values, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateBetween(Date value1, Date value2) {
            addCriterion("transdate between", value1, value2, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateNotBetween(Date value1, Date value2) {
            addCriterion("transdate not between", value1, value2, "transdate");
            return (Criteria) this;
        }

        public Criteria andTranstimeIsNull() {
            addCriterion("transtime is null");
            return (Criteria) this;
        }

        public Criteria andTranstimeIsNotNull() {
            addCriterion("transtime is not null");
            return (Criteria) this;
        }

        public Criteria andTranstimeEqualTo(String value) {
            addCriterion("transtime =", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotEqualTo(String value) {
            addCriterion("transtime <>", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeGreaterThan(String value) {
            addCriterion("transtime >", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeGreaterThanOrEqualTo(String value) {
            addCriterion("transtime >=", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeLessThan(String value) {
            addCriterion("transtime <", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeLessThanOrEqualTo(String value) {
            addCriterion("transtime <=", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeLike(String value) {
            addCriterion("transtime like", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotLike(String value) {
            addCriterion("transtime not like", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeIn(List<String> values) {
            addCriterion("transtime in", values, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotIn(List<String> values) {
            addCriterion("transtime not in", values, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeBetween(String value1, String value2) {
            addCriterion("transtime between", value1, value2, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotBetween(String value1, String value2) {
            addCriterion("transtime not between", value1, value2, "transtime");
            return (Criteria) this;
        }

        public Criteria andManagecomIsNull() {
            addCriterion("managecom is null");
            return (Criteria) this;
        }

        public Criteria andManagecomIsNotNull() {
            addCriterion("managecom is not null");
            return (Criteria) this;
        }

        public Criteria andManagecomEqualTo(String value) {
            addCriterion("managecom =", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomNotEqualTo(String value) {
            addCriterion("managecom <>", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomGreaterThan(String value) {
            addCriterion("managecom >", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomGreaterThanOrEqualTo(String value) {
            addCriterion("managecom >=", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomLessThan(String value) {
            addCriterion("managecom <", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomLessThanOrEqualTo(String value) {
            addCriterion("managecom <=", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomLike(String value) {
            addCriterion("managecom like", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomNotLike(String value) {
            addCriterion("managecom not like", value, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomIn(List<String> values) {
            addCriterion("managecom in", values, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomNotIn(List<String> values) {
            addCriterion("managecom not in", values, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomBetween(String value1, String value2) {
            addCriterion("managecom between", value1, value2, "managecom");
            return (Criteria) this;
        }

        public Criteria andManagecomNotBetween(String value1, String value2) {
            addCriterion("managecom not between", value1, value2, "managecom");
            return (Criteria) this;
        }

        public Criteria andRiskcodeIsNull() {
            addCriterion("riskcode is null");
            return (Criteria) this;
        }

        public Criteria andRiskcodeIsNotNull() {
            addCriterion("riskcode is not null");
            return (Criteria) this;
        }

        public Criteria andRiskcodeEqualTo(String value) {
            addCriterion("riskcode =", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeNotEqualTo(String value) {
            addCriterion("riskcode <>", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeGreaterThan(String value) {
            addCriterion("riskcode >", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeGreaterThanOrEqualTo(String value) {
            addCriterion("riskcode >=", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeLessThan(String value) {
            addCriterion("riskcode <", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeLessThanOrEqualTo(String value) {
            addCriterion("riskcode <=", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeLike(String value) {
            addCriterion("riskcode like", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeNotLike(String value) {
            addCriterion("riskcode not like", value, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeIn(List<String> values) {
            addCriterion("riskcode in", values, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeNotIn(List<String> values) {
            addCriterion("riskcode not in", values, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeBetween(String value1, String value2) {
            addCriterion("riskcode between", value1, value2, "riskcode");
            return (Criteria) this;
        }

        public Criteria andRiskcodeNotBetween(String value1, String value2) {
            addCriterion("riskcode not between", value1, value2, "riskcode");
            return (Criteria) this;
        }

        public Criteria andProposalNoIsNull() {
            addCriterion("proposal_no is null");
            return (Criteria) this;
        }

        public Criteria andProposalNoIsNotNull() {
            addCriterion("proposal_no is not null");
            return (Criteria) this;
        }

        public Criteria andProposalNoEqualTo(String value) {
            addCriterion("proposal_no =", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoNotEqualTo(String value) {
            addCriterion("proposal_no <>", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoGreaterThan(String value) {
            addCriterion("proposal_no >", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoGreaterThanOrEqualTo(String value) {
            addCriterion("proposal_no >=", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoLessThan(String value) {
            addCriterion("proposal_no <", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoLessThanOrEqualTo(String value) {
            addCriterion("proposal_no <=", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoLike(String value) {
            addCriterion("proposal_no like", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoNotLike(String value) {
            addCriterion("proposal_no not like", value, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoIn(List<String> values) {
            addCriterion("proposal_no in", values, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoNotIn(List<String> values) {
            addCriterion("proposal_no not in", values, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoBetween(String value1, String value2) {
            addCriterion("proposal_no between", value1, value2, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andProposalNoNotBetween(String value1, String value2) {
            addCriterion("proposal_no not between", value1, value2, "proposalNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoIsNull() {
            addCriterion("prt_no is null");
            return (Criteria) this;
        }

        public Criteria andPrtNoIsNotNull() {
            addCriterion("prt_no is not null");
            return (Criteria) this;
        }

        public Criteria andPrtNoEqualTo(String value) {
            addCriterion("prt_no =", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoNotEqualTo(String value) {
            addCriterion("prt_no <>", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoGreaterThan(String value) {
            addCriterion("prt_no >", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoGreaterThanOrEqualTo(String value) {
            addCriterion("prt_no >=", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoLessThan(String value) {
            addCriterion("prt_no <", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoLessThanOrEqualTo(String value) {
            addCriterion("prt_no <=", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoLike(String value) {
            addCriterion("prt_no like", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoNotLike(String value) {
            addCriterion("prt_no not like", value, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoIn(List<String> values) {
            addCriterion("prt_no in", values, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoNotIn(List<String> values) {
            addCriterion("prt_no not in", values, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoBetween(String value1, String value2) {
            addCriterion("prt_no between", value1, value2, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPrtNoNotBetween(String value1, String value2) {
            addCriterion("prt_no not between", value1, value2, "prtNo");
            return (Criteria) this;
        }

        public Criteria andPolNoIsNull() {
            addCriterion("pol_no is null");
            return (Criteria) this;
        }

        public Criteria andPolNoIsNotNull() {
            addCriterion("pol_no is not null");
            return (Criteria) this;
        }

        public Criteria andPolNoEqualTo(String value) {
            addCriterion("pol_no =", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoNotEqualTo(String value) {
            addCriterion("pol_no <>", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoGreaterThan(String value) {
            addCriterion("pol_no >", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoGreaterThanOrEqualTo(String value) {
            addCriterion("pol_no >=", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoLessThan(String value) {
            addCriterion("pol_no <", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoLessThanOrEqualTo(String value) {
            addCriterion("pol_no <=", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoLike(String value) {
            addCriterion("pol_no like", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoNotLike(String value) {
            addCriterion("pol_no not like", value, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoIn(List<String> values) {
            addCriterion("pol_no in", values, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoNotIn(List<String> values) {
            addCriterion("pol_no not in", values, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoBetween(String value1, String value2) {
            addCriterion("pol_no between", value1, value2, "polNo");
            return (Criteria) this;
        }

        public Criteria andPolNoNotBetween(String value1, String value2) {
            addCriterion("pol_no not between", value1, value2, "polNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoIsNull() {
            addCriterion("edor_no is null");
            return (Criteria) this;
        }

        public Criteria andEdorNoIsNotNull() {
            addCriterion("edor_no is not null");
            return (Criteria) this;
        }

        public Criteria andEdorNoEqualTo(String value) {
            addCriterion("edor_no =", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoNotEqualTo(String value) {
            addCriterion("edor_no <>", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoGreaterThan(String value) {
            addCriterion("edor_no >", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoGreaterThanOrEqualTo(String value) {
            addCriterion("edor_no >=", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoLessThan(String value) {
            addCriterion("edor_no <", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoLessThanOrEqualTo(String value) {
            addCriterion("edor_no <=", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoLike(String value) {
            addCriterion("edor_no like", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoNotLike(String value) {
            addCriterion("edor_no not like", value, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoIn(List<String> values) {
            addCriterion("edor_no in", values, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoNotIn(List<String> values) {
            addCriterion("edor_no not in", values, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoBetween(String value1, String value2) {
            addCriterion("edor_no between", value1, value2, "edorNo");
            return (Criteria) this;
        }

        public Criteria andEdorNoNotBetween(String value1, String value2) {
            addCriterion("edor_no not between", value1, value2, "edorNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoIsNull() {
            addCriterion("tempfee_no is null");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoIsNotNull() {
            addCriterion("tempfee_no is not null");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoEqualTo(String value) {
            addCriterion("tempfee_no =", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoNotEqualTo(String value) {
            addCriterion("tempfee_no <>", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoGreaterThan(String value) {
            addCriterion("tempfee_no >", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoGreaterThanOrEqualTo(String value) {
            addCriterion("tempfee_no >=", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoLessThan(String value) {
            addCriterion("tempfee_no <", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoLessThanOrEqualTo(String value) {
            addCriterion("tempfee_no <=", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoLike(String value) {
            addCriterion("tempfee_no like", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoNotLike(String value) {
            addCriterion("tempfee_no not like", value, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoIn(List<String> values) {
            addCriterion("tempfee_no in", values, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoNotIn(List<String> values) {
            addCriterion("tempfee_no not in", values, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoBetween(String value1, String value2) {
            addCriterion("tempfee_no between", value1, value2, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTempfeeNoNotBetween(String value1, String value2) {
            addCriterion("tempfee_no not between", value1, value2, "tempfeeNo");
            return (Criteria) this;
        }

        public Criteria andTransAmntIsNull() {
            addCriterion("trans_amnt is null");
            return (Criteria) this;
        }

        public Criteria andTransAmntIsNotNull() {
            addCriterion("trans_amnt is not null");
            return (Criteria) this;
        }

        public Criteria andTransAmntEqualTo(BigDecimal value) {
            addCriterion("trans_amnt =", value, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntNotEqualTo(BigDecimal value) {
            addCriterion("trans_amnt <>", value, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntGreaterThan(BigDecimal value) {
            addCriterion("trans_amnt >", value, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trans_amnt >=", value, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntLessThan(BigDecimal value) {
            addCriterion("trans_amnt <", value, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trans_amnt <=", value, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntIn(List<BigDecimal> values) {
            addCriterion("trans_amnt in", values, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntNotIn(List<BigDecimal> values) {
            addCriterion("trans_amnt not in", values, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trans_amnt between", value1, value2, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andTransAmntNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trans_amnt not between", value1, value2, "transAmnt");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNull() {
            addCriterion("bank_account is null");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNotNull() {
            addCriterion("bank_account is not null");
            return (Criteria) this;
        }

        public Criteria andBankAccountEqualTo(String value) {
            addCriterion("bank_account =", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotEqualTo(String value) {
            addCriterion("bank_account <>", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThan(String value) {
            addCriterion("bank_account >", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("bank_account >=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThan(String value) {
            addCriterion("bank_account <", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThanOrEqualTo(String value) {
            addCriterion("bank_account <=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLike(String value) {
            addCriterion("bank_account like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotLike(String value) {
            addCriterion("bank_account not like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountIn(List<String> values) {
            addCriterion("bank_account in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotIn(List<String> values) {
            addCriterion("bank_account not in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountBetween(String value1, String value2) {
            addCriterion("bank_account between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotBetween(String value1, String value2) {
            addCriterion("bank_account not between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andRcodeIsNull() {
            addCriterion("rcode is null");
            return (Criteria) this;
        }

        public Criteria andRcodeIsNotNull() {
            addCriterion("rcode is not null");
            return (Criteria) this;
        }

        public Criteria andRcodeEqualTo(String value) {
            addCriterion("rcode =", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeNotEqualTo(String value) {
            addCriterion("rcode <>", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeGreaterThan(String value) {
            addCriterion("rcode >", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeGreaterThanOrEqualTo(String value) {
            addCriterion("rcode >=", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeLessThan(String value) {
            addCriterion("rcode <", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeLessThanOrEqualTo(String value) {
            addCriterion("rcode <=", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeLike(String value) {
            addCriterion("rcode like", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeNotLike(String value) {
            addCriterion("rcode not like", value, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeIn(List<String> values) {
            addCriterion("rcode in", values, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeNotIn(List<String> values) {
            addCriterion("rcode not in", values, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeBetween(String value1, String value2) {
            addCriterion("rcode between", value1, value2, "rcode");
            return (Criteria) this;
        }

        public Criteria andRcodeNotBetween(String value1, String value2) {
            addCriterion("rcode not between", value1, value2, "rcode");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNull() {
            addCriterion("trans_status is null");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNotNull() {
            addCriterion("trans_status is not null");
            return (Criteria) this;
        }

        public Criteria andTransStatusEqualTo(String value) {
            addCriterion("trans_status =", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotEqualTo(String value) {
            addCriterion("trans_status <>", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThan(String value) {
            addCriterion("trans_status >", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThanOrEqualTo(String value) {
            addCriterion("trans_status >=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThan(String value) {
            addCriterion("trans_status <", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThanOrEqualTo(String value) {
            addCriterion("trans_status <=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLike(String value) {
            addCriterion("trans_status like", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotLike(String value) {
            addCriterion("trans_status not like", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusIn(List<String> values) {
            addCriterion("trans_status in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotIn(List<String> values) {
            addCriterion("trans_status not in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusBetween(String value1, String value2) {
            addCriterion("trans_status between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotBetween(String value1, String value2) {
            addCriterion("trans_status not between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDescrIsNull() {
            addCriterion("descr is null");
            return (Criteria) this;
        }

        public Criteria andDescrIsNotNull() {
            addCriterion("descr is not null");
            return (Criteria) this;
        }

        public Criteria andDescrEqualTo(String value) {
            addCriterion("descr =", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotEqualTo(String value) {
            addCriterion("descr <>", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThan(String value) {
            addCriterion("descr >", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThanOrEqualTo(String value) {
            addCriterion("descr >=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThan(String value) {
            addCriterion("descr <", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThanOrEqualTo(String value) {
            addCriterion("descr <=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLike(String value) {
            addCriterion("descr like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotLike(String value) {
            addCriterion("descr not like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrIn(List<String> values) {
            addCriterion("descr in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotIn(List<String> values) {
            addCriterion("descr not in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrBetween(String value1, String value2) {
            addCriterion("descr between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotBetween(String value1, String value2) {
            addCriterion("descr not between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andTempIsNull() {
            addCriterion("temp is null");
            return (Criteria) this;
        }

        public Criteria andTempIsNotNull() {
            addCriterion("temp is not null");
            return (Criteria) this;
        }

        public Criteria andTempEqualTo(String value) {
            addCriterion("temp =", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotEqualTo(String value) {
            addCriterion("temp <>", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThan(String value) {
            addCriterion("temp >", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThanOrEqualTo(String value) {
            addCriterion("temp >=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThan(String value) {
            addCriterion("temp <", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThanOrEqualTo(String value) {
            addCriterion("temp <=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLike(String value) {
            addCriterion("temp like", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotLike(String value) {
            addCriterion("temp not like", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempIn(List<String> values) {
            addCriterion("temp in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotIn(List<String> values) {
            addCriterion("temp not in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempBetween(String value1, String value2) {
            addCriterion("temp between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotBetween(String value1, String value2) {
            addCriterion("temp not between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andClientIpIsNull() {
            addCriterion("client_ip is null");
            return (Criteria) this;
        }

        public Criteria andClientIpIsNotNull() {
            addCriterion("client_ip is not null");
            return (Criteria) this;
        }

        public Criteria andClientIpEqualTo(String value) {
            addCriterion("client_ip =", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotEqualTo(String value) {
            addCriterion("client_ip <>", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpGreaterThan(String value) {
            addCriterion("client_ip >", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpGreaterThanOrEqualTo(String value) {
            addCriterion("client_ip >=", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLessThan(String value) {
            addCriterion("client_ip <", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLessThanOrEqualTo(String value) {
            addCriterion("client_ip <=", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLike(String value) {
            addCriterion("client_ip like", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotLike(String value) {
            addCriterion("client_ip not like", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpIn(List<String> values) {
            addCriterion("client_ip in", values, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotIn(List<String> values) {
            addCriterion("client_ip not in", values, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpBetween(String value1, String value2) {
            addCriterion("client_ip between", value1, value2, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotBetween(String value1, String value2) {
            addCriterion("client_ip not between", value1, value2, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientPortIsNull() {
            addCriterion("client_port is null");
            return (Criteria) this;
        }

        public Criteria andClientPortIsNotNull() {
            addCriterion("client_port is not null");
            return (Criteria) this;
        }

        public Criteria andClientPortEqualTo(String value) {
            addCriterion("client_port =", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortNotEqualTo(String value) {
            addCriterion("client_port <>", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortGreaterThan(String value) {
            addCriterion("client_port >", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortGreaterThanOrEqualTo(String value) {
            addCriterion("client_port >=", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortLessThan(String value) {
            addCriterion("client_port <", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortLessThanOrEqualTo(String value) {
            addCriterion("client_port <=", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortLike(String value) {
            addCriterion("client_port like", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortNotLike(String value) {
            addCriterion("client_port not like", value, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortIn(List<String> values) {
            addCriterion("client_port in", values, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortNotIn(List<String> values) {
            addCriterion("client_port not in", values, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortBetween(String value1, String value2) {
            addCriterion("client_port between", value1, value2, "clientPort");
            return (Criteria) this;
        }

        public Criteria andClientPortNotBetween(String value1, String value2) {
            addCriterion("client_port not between", value1, value2, "clientPort");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeIsNull() {
            addCriterion("service_starttime is null");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeIsNotNull() {
            addCriterion("service_starttime is not null");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeEqualTo(Date value) {
            addCriterion("service_starttime =", value, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeNotEqualTo(Date value) {
            addCriterion("service_starttime <>", value, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeGreaterThan(Date value) {
            addCriterion("service_starttime >", value, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("service_starttime >=", value, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeLessThan(Date value) {
            addCriterion("service_starttime <", value, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("service_starttime <=", value, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeIn(List<Date> values) {
            addCriterion("service_starttime in", values, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeNotIn(List<Date> values) {
            addCriterion("service_starttime not in", values, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeBetween(Date value1, Date value2) {
            addCriterion("service_starttime between", value1, value2, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("service_starttime not between", value1, value2, "serviceStarttime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeIsNull() {
            addCriterion("service_endtime is null");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeIsNotNull() {
            addCriterion("service_endtime is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeEqualTo(Date value) {
            addCriterion("service_endtime =", value, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeNotEqualTo(Date value) {
            addCriterion("service_endtime <>", value, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeGreaterThan(Date value) {
            addCriterion("service_endtime >", value, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("service_endtime >=", value, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeLessThan(Date value) {
            addCriterion("service_endtime <", value, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("service_endtime <=", value, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeIn(List<Date> values) {
            addCriterion("service_endtime in", values, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeNotIn(List<Date> values) {
            addCriterion("service_endtime not in", values, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeBetween(Date value1, Date value2) {
            addCriterion("service_endtime between", value1, value2, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andServiceEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("service_endtime not between", value1, value2, "serviceEndtime");
            return (Criteria) this;
        }

        public Criteria andMakedateIsNull() {
            addCriterion("makedate is null");
            return (Criteria) this;
        }

        public Criteria andMakedateIsNotNull() {
            addCriterion("makedate is not null");
            return (Criteria) this;
        }

        public Criteria andMakedateEqualTo(Date value) {
            addCriterion("makedate =", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotEqualTo(Date value) {
            addCriterion("makedate <>", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateGreaterThan(Date value) {
            addCriterion("makedate >", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateGreaterThanOrEqualTo(Date value) {
            addCriterion("makedate >=", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateLessThan(Date value) {
            addCriterion("makedate <", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateLessThanOrEqualTo(Date value) {
            addCriterion("makedate <=", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateIn(List<Date> values) {
            addCriterion("makedate in", values, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotIn(List<Date> values) {
            addCriterion("makedate not in", values, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateBetween(Date value1, Date value2) {
            addCriterion("makedate between", value1, value2, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotBetween(Date value1, Date value2) {
            addCriterion("makedate not between", value1, value2, "makedate");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNull() {
            addCriterion("maketime is null");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNotNull() {
            addCriterion("maketime is not null");
            return (Criteria) this;
        }

        public Criteria andMaketimeEqualTo(String value) {
            addCriterion("maketime =", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotEqualTo(String value) {
            addCriterion("maketime <>", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThan(String value) {
            addCriterion("maketime >", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThanOrEqualTo(String value) {
            addCriterion("maketime >=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThan(String value) {
            addCriterion("maketime <", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThanOrEqualTo(String value) {
            addCriterion("maketime <=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLike(String value) {
            addCriterion("maketime like", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotLike(String value) {
            addCriterion("maketime not like", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeIn(List<String> values) {
            addCriterion("maketime in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotIn(List<String> values) {
            addCriterion("maketime not in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeBetween(String value1, String value2) {
            addCriterion("maketime between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotBetween(String value1, String value2) {
            addCriterion("maketime not between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("modifydate is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("modifydate is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("modifydate =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("modifydate <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("modifydate >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifydate >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("modifydate <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("modifydate <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("modifydate in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("modifydate not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("modifydate between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("modifydate not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNull() {
            addCriterion("modifytime is null");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNotNull() {
            addCriterion("modifytime is not null");
            return (Criteria) this;
        }

        public Criteria andModifytimeEqualTo(String value) {
            addCriterion("modifytime =", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotEqualTo(String value) {
            addCriterion("modifytime <>", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThan(String value) {
            addCriterion("modifytime >", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThanOrEqualTo(String value) {
            addCriterion("modifytime >=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThan(String value) {
            addCriterion("modifytime <", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThanOrEqualTo(String value) {
            addCriterion("modifytime <=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLike(String value) {
            addCriterion("modifytime like", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotLike(String value) {
            addCriterion("modifytime not like", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIn(List<String> values) {
            addCriterion("modifytime in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotIn(List<String> values) {
            addCriterion("modifytime not in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeBetween(String value1, String value2) {
            addCriterion("modifytime between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotBetween(String value1, String value2) {
            addCriterion("modifytime not between", value1, value2, "modifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LKTransStatus
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 19 18:16:07 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}