package com.sinosoft.dao.ybt;

import com.sinosoft.ybtentity.Lktransstatus;
import com.sinosoft.ybtentity.LktransstatusExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface LktransstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    int countByExample(LktransstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    int deleteByExample(LktransstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    int insert(Lktransstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    int insertSelective(Lktransstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    List<Lktransstatus> selectByExample(LktransstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") Lktransstatus record, @Param("example") LktransstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LKTransStatus
     *
     * @mbggenerated Fri Feb 19 18:16:07 CST 2021
     */
    int updateByExample(@Param("record") Lktransstatus record, @Param("example") LktransstatusExample example);
}