# 设置服务端口
server:
  port: 8001

#设置eureka相关信息
eureka:
  instance:
    # 设置实例地址
    hostname: localhost
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    fetch-registry: false

    serviceUrl:
      defaultZone: http://localhost:8001/eureka/


# 服务模块名称
spring:
  application:
    name: ybtServerDiscover